import type { HamrobazaarListing } from "./hamrobazaar";

/**
 * Fallback dataset used when the live Hamrobazaar API is unreachable
 * (anti-bot blocks, network issues). Realistic Nepali listings so the
 * dashboard always demonstrates the full pipeline. Clearly flagged as
 * "sample" in the UI — never silently presented as live data.
 */
export const SAMPLE_HAMROBAZAAR_LISTINGS: HamrobazaarListing[] = [
  {
    id: "SAMPLE-001",
    title: "1-4-0 Aana Land for Sale at Koteshwor",
    price: 27500000,
    categoryName: "For Sale — Land",
    location: "Koteshwor, Kathmandu Metropolitan City, Kathmandu",
    latitude: 27.6796,
    longitude: 85.3477,
    imageUrl: null,
    description:
      "Corner plot with 20 ft road access, all legal documents ready. Suitable for apartment or duplex construction. East facing, ring road proximity.",
    createdTime: "2 hours ago",
    seller: "Sunrise Developers",
    negotiable: true,
    condition: "Other",
    detailUrl: "/detail/for-sale-land/1-4-0-aana-land-for-sale-at-koteshwor/SAMPLE-001",
  },
  {
    id: "SAMPLE-002",
    title: "Modern 3-Bedroom Apartment for Rent in Baluwatar",
    price: 65000,
    categoryName: "For Rent — Flat & Apartment",
    location: "Baluwatar, Kathmandu Metropolitan City, Kathmandu",
    latitude: 27.7291,
    longitude: 85.3286,
    imageUrl: null,
    description:
      "3BHK with attached bathrooms, modular kitchen, covered parking and 24/7 security. Family-friendly building with lift and backup power.",
    createdTime: "5 hours ago",
    seller: "Lalit Memorial Realty",
    negotiable: false,
    condition: "Used / Secondhand",
    detailUrl: "/detail/for-rent-flat-apartment/modern-3-bedroom-apartment-for-rent-in-baluwatar/SAMPLE-002",
  },
  {
    id: "SAMPLE-003",
    title: "12 Anna Agricultural Land, Godawari",
    price: 18500000,
    categoryName: "For Sale — Land",
    location: "Godawari, Lalitpur",
    latitude: 27.5952,
    longitude: 85.3881,
    imageUrl: null,
    description:
      "Level agricultural land near Godawari Botanical Garden. Ideal for farmhouse or institutional use. Water source available year-round.",
    createdTime: "1 day ago",
    seller: "Anand Karki",
    negotiable: true,
    condition: "Other",
    detailUrl: "/detail/for-sale-land/12-anna-agricultural-land-godawari/SAMPLE-003",
  },
  {
    id: "SAMPLE-004",
    title: "Ground Floor Shop Space for Rent, New Road",
    price: 95000,
    categoryName: "For Rent — Shutter & Shop Space",
    location: "New Road, Kathmandu Metropolitan City, Kathmandu",
    latitude: 27.7037,
    longitude: 85.3092,
    imageUrl: null,
    description:
      "Prime retail location, 400 sq ft with shutter, display window and mezzanine. High foot traffic opposite City Hall. 3-year lease preferred.",
    createdTime: "1 day ago",
    seller: "Ranjana Traders",
    negotiable: false,
    condition: "Used / Secondhand",
    detailUrl: "/detail/for-rent-shutter-shop-space/ground-floor-shop-space-for-rent-new-road/SAMPLE-004",
  },
  {
    id: "SAMPLE-005",
    title: "5-Story Commercial Building for Sale, Putalisadak",
    price: 145000000,
    categoryName: "For Sale — Commercial Building",
    location: "Putalisadak, Kathmandu Metropolitan City, Kathmandu",
    latitude: 27.7095,
    longitude: 85.3203,
    imageUrl: null,
    description:
      "Fully rented commercial building, 5 floors with basement parking. Stable monthly rental income. Bank finance available. All documents clear.",
    createdTime: "2 days ago",
    seller: "Timsina Properties",
    negotiable: true,
    condition: "Used / Secondhand",
    detailUrl: "/detail/for-sale-commercial-building/5-story-commercial-building-for-sale-putalisadak/SAMPLE-005",
  },
  {
    id: "SAMPLE-006",
    title: "2 BHK Apartment for Sale, Imadol",
    price: 13500000,
    categoryName: "For Sale — Apartment",
    location: "Imadol, Lalitpur",
    latitude: 27.6662,
    longitude: 85.3316,
    imageUrl: null,
    description:
      "South-facing 2BHK, 1,050 sq ft carpet area, lift, parking and community hall. Possession within 6 months. Ideal first home or investment.",
    createdTime: "2 days ago",
    seller: "Nepal Dwellings",
    negotiable: true,
    condition: "Brand New",
    detailUrl: "/detail/for-sale-apartment/2-bhk-apartment-for-sale-imadol/SAMPLE-006",
  },
  {
    id: "SAMPLE-007",
    title: "Independent House for Rent, Baneshwor",
    price: 120000,
    categoryName: "For Rent — House",
    location: "Baneshwor, Kathmandu Metropolitan City, Kathmandu",
    latitude: 27.6934,
    longitude: 85.3359,
    imageUrl: null,
    description:
      "Newly built 4-bedroom independent house with garden, 2 parking spaces and servant quarter. Ideal for families or embassy staff.",
    createdTime: "3 days ago",
    seller: "House of Karma",
    negotiable: false,
    condition: "Brand New",
    detailUrl: "/detail/for-rent-house/independent-house-for-rent-baneshwor/SAMPLE-007",
  },
  {
    id: "SAMPLE-008",
    title: "Open Land for Rent, Ring Road Near Satdobato",
    price: 85000,
    categoryName: "For Rent — Land",
    location: "Satdobato, Lalitpur",
    latitude: 27.65,
    longitude: 85.3155,
    imageUrl: null,
    description:
      "2 ropani open land adjacent to ring road. Suitable for showroom, warehouse or event space. 5-year contract, easy road access.",
    createdTime: "4 days ago",
    seller: "Basnet Group",
    negotiable: true,
    condition: "Other",
    detailUrl: "/detail/for-rent-land/open-land-for-rent-ring-road-near-satdobato/SAMPLE-008",
  },
];
