"use client";

import { cva, type VariantProps } from "class-variance-authority";
import type { LucideIcon } from "lucide-react";
import {
  Archive,
  ArrowLeftRight,
  ArrowRight,
  ArrowUp,
  ArrowUpRight,
  BadgeCheck,
  BarChart3,
  Bookmark,
  Bed,
  Briefcase,
  Building,
  Building2,
  Calculator,
  Calendar,
  CalendarClock,
  Camera,
  Check,
  CheckCircle,
  CheckSquare,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleAlert,
  CircleX,
  ClipboardList,
  Clock,
  CloudOff,
  Copy,
  Cpu,
  CreditCard,
  Download,
  Edit,
  Expand,
  ExternalLink,
  Eye,
  EyeOff,
  Factory,
  FileText,
  FileUp,
  Filter,
  GripVertical,
  Folder,
  Gavel,
  Globe,
  GraduationCap,
  Handshake,
  HardHat,
  Heart,
  HelpCircle,
  History,
  Home,
  Hospital,
  Hotel,
  Image,
  Images,
  Info,
  Landmark,
  Layers,
  LayoutDashboard,
  LayoutGrid,
  Leaf,
  ListFilter,
  Loader2,
  LocateFixed,
  Lock,
  Mail,
  Map,
  MapPin,
  Maximize2,
  Menu,
  MessageCircle,
  MessageSquare,
  Minus,
  MoreVertical,
  Mountain,
  Navigation,
  Phone,
  PhoneCall,
  Plane,
  Play,
  PlayCircle,
  Plus,
  Podium,
  Receipt,
  RefreshCw,
  Reply,
  Scale,
  School,
  Search,
  Send,
  Shield,
  ShieldCheck,
  ShieldQuestion,
  ShoppingBag,
  ShoppingCart,
  SortAsc,
  Store,
  Tag,
  Timeline,
  Trash2,
  TrendingDown,
  TrendingUp,
  TriangleAlert,
  Truck,
  UserCog,
  Users,
  Utensils,
  Video,
  Warehouse,
  Wrench,
  X,
  ZoomIn,
} from "lucide-react";
import React from "react";

import { cn } from "../lib/utils";

const iconVariants = cva("", {
  variants: {
    size: {
      sm: "text-data-table",
      md: "text-[24px]",
      lg: "text-data-price",
      xl: "text-[40px]",
    },
  },
  defaultVariants: {
    size: "md",
  },
});

interface IconProps
  extends React.SVGProps<SVGSVGElement>, VariantProps<typeof iconVariants> {
  name: string;
  filled?: boolean;
}

const ICON_MAP: Record<string, LucideIcon> = {
  add: Plus,
  add_shopping_cart: ShoppingCart,
  arrow_forward: ArrowRight,
  arrow_outward: ArrowUpRight,
  arrow_upward: ArrowUp,
  cancel: CircleX,
  chevron_down: ChevronDown,
  chevron_left: ChevronLeft,
  chevron_right: ChevronRight,
  close: X,
  expand_more: ChevronDown,
  more_vert: MoreVertical,
  open_in_new: ExternalLink,
  refresh: RefreshCw,
  reload: RefreshCw,
  remove: Minus,
  reply: Reply,
  send: Send,
  sort: SortAsc,
  sort_asc: SortAsc,
  swap_horiz: ArrowLeftRight,

  account_balance: Landmark,
  agriculture: Leaf,
  analytics: BarChart3,
  apartment: Building,
  archive: Archive,
  badge: BadgeCheck,
  balance: Scale,
  bed: Bed,
  bookmark: Bookmark,
  build: Wrench,
  business_center: Briefcase,
  calculate: Calculator,
  checklist: ClipboardList,
  check: Check,
  check_circle: CheckCircle,
  chat: MessageSquare,
  cloud_off: CloudOff,
  community: Users,
  construction: HardHat,
  content_copy: Copy,
  credit_card: CreditCard,
  delete: Trash2,
  delete_forever: Trash2,
  description: FileText,
  directions: Navigation,
  domain: Landmark,
  download: Download,
  drag_indicator: GripVertical,
  drive_file_rename_outline: Edit,
  edit: Edit,
  education: GraduationCap,
  email: Mail,
  error: CircleAlert,
  event: Calendar,
  event_repeat: CalendarClock,
  expand: Expand,
  factory: Factory,
  favorite: Heart,
  filter: Filter,
  filter_alt: Filter,
  filter_list: ListFilter,
  flight: Plane,
  folder: Folder,
  forum: MessageCircle,
  fullscreen: Maximize2,
  gavel: Gavel,
  gpp_maybe: ShieldQuestion,
  grid_view: LayoutGrid,
  groups: Users,
  handshake: Handshake,
  healthcare: Hospital,
  help: HelpCircle,
  help_outline: HelpCircle,
  history: History,
  home: Home,
  hospitality: Hotel,
  hotel: Hotel,
  image: Image,
  images: Images,
  industrial: Factory,
  info: Info,
  inventory: ClipboardList,
  landscape: Mountain,
  layers: Layers,
  list_alt: ClipboardList,
  local_hospital: Hospital,
  local_shipping: Truck,
  location_city: Building2,
  location_on: MapPin,
  lock: Lock,
  mail: Mail,
  manage_accounts: UserCog,
  map: Map,
  Menu,
  more_vert_2: MoreVertical,
  my_location: LocateFixed,
  office: Briefcase,
  PhoneCall,
  phone: Phone,
  photo_camera: Camera,
  photo_library: Images,
  play_arrow: Play,
  play_circle: PlayCircle,
  Podium: Podium,
  precision_manufacturing: Cpu,
  progress_activity: Loader2,
  public: Globe,
  receipt_long: Receipt,
  restaurant: Utensils,
  retail_space: ShoppingBag,
  room: Bed,
  schedule: Clock,
  school: School,
  search: Search,
  security: ShieldCheck,
  sell: Tag,
  shield: Shield,
  shopping_bag: ShoppingBag,
  space_dashboard: LayoutDashboard,
  special_purpose: School,
  storefront: Store,
  task_alt: CheckSquare,
  terrain: Mountain,
  timeline: Timeline,
  trending_down: TrendingDown,
  trending_flat: ArrowRight,
  trending_up: TrendingUp,
  upload_file: FileUp,
  verified: ShieldCheck,
  verified_user: ShieldCheck,
  videocam: Video,
  visibility: Eye,
  visibility_off: EyeOff,
  warehouse: Warehouse,
  warning: TriangleAlert,
  workshop: Wrench,
  zoom_in: ZoomIn,
  alarm: Clock,
  article: FileText,
};

const FALLBACK: LucideIcon = HelpCircle;

const Icon = React.forwardRef<SVGSVGElement, IconProps>(
  ({ name, size = "md", filled = false, className, ...props }, ref) => {
    const Icon = ICON_MAP[name] ?? FALLBACK;
    return (
      <Icon
        ref={ref}
        size="1em"
        fill={filled ? "currentColor" : "none"}
        strokeWidth={filled ? 1 : 2}
        className={cn(iconVariants({ size, className }))}
        {...props}
      />
    );
  },
);

Icon.displayName = "Icon";

export { Icon, iconVariants };
export type { IconProps };
