import { InputType, Field } from '@nestjs/graphql';
import {
  IsBoolean,
  IsEnum,
  IsNumber,
  IsOptional,
  IsString,
  IsNotEmpty,
  MaxLength,
} from 'class-validator';
import {
  FacingDirection,
  PropertyType,
  RoadType,
} from '@repo/db';

/**
 * Client payload for creating a property. Used by BOTH the REST controller and
 * the GraphQL resolver (one class, both transports).
 *
 * `ownerId`, `listingCode` and `slug` are intentionally NOT in the input:
 *  - `ownerId` comes from the authenticated user (@CurrentUser), never the body
 *  - `listingCode` and `slug` are generated by the service (business logic)
 */
@InputType()
export class CreatePropertyInput {
    @Field(() => String)
  @IsString()
  @IsNotEmpty()
  @MaxLength(200)
  title!: string;

  @Field(() => String, { nullable: true })
  @IsString()
  @IsOptional()
  @MaxLength(5000)
  description?: string;

  @Field(() => PropertyType)
  @IsEnum(PropertyType)
  propertyType!: PropertyType;

  @Field(() => Number)
  @IsNumber()
  askingPrice!: number;

  @Field(() => Number, { nullable: true })
  @IsNumber()
  @IsOptional()
  pricePerAana?: number;

  @Field(() => Number, { nullable: true })
  @IsNumber()
  @IsOptional()
  roadAccessWidthFt?: number;

  @Field(() => RoadType, { nullable: true })
  @IsEnum(RoadType)
  @IsOptional()
  roadType?: RoadType;

  @Field(() => FacingDirection, { nullable: true })
  @IsEnum(FacingDirection)
  @IsOptional()
  facing?: FacingDirection;

  @Field(() => Boolean, { nullable: true })
  @IsBoolean()
  @IsOptional()
  isCornerPlot?: boolean;

  @Field(() => String, { nullable: true })
  @IsString()
  @IsOptional()
  agentId?: string;
}
